### ISSUE TITLE
who is responsible to update the resource-config.txt file

### ISSUE THREAD

**Issue by koalaxiu7** [NTHU-LSALAB/Gemini#3]
I find the listener of resource-config.txt and don't find the code to write and update the resource-config.txt, could you show me the filename of the code? Thanks

**Comment by jim90247** [comment]
Sorry for the late reply.
Resource config file (`resource-config.txt`) is typically updated by user via text editor or other program outside Gemini.
Scheduler will monitor this change and update inner data structure.
