### ISSUE TITLE
Compile Failed

### ISSUE THREAD

**Issue by XutongLi** [NTHU-LSALAB/Gemini#5]
datasvm@datasvm-linux:~/Gemini/src$ make  DEBUG=1

make[1]: Entering directory '/home/datasvm/Gemini/src/comm'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/datasvm/Gemini/src/comm'
/usr/local/cuda/bin/nvcc -ccbin /anaconda/envs/py37_default/bin/x86_64-conda_cos6-linux-gnu-c++ hook.o predictor.o debug.o comm/endpoint.o comm/message.o comm/request.o comm/response.o \
        -shared -m64 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -lcuda -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib64/stubs -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/anaconda/envs/py37_default/lib -Wl,-rpath-link,/anaconda/envs/py37_default/lib -L/anaconda/envs/py37_default/lib -ldl -lrt -L/usr/local/lib -lzmq -lglib-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -o libgemhook.so.1
nvcc fatal   : Unknown option 'Wl,-O2'
Makefile:64: recipe for target 'libgemhook.so.1' failed
make: *** [libgemhook.so.1] Error 1

***

How to solve this problem?

**Comment by jim90247** [comment]
From [Red Hat Developer Guide (Section 16.6)](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/developer_guide/gcc-using-libraries#gcc-using-libraries_using-both-static-dynamic-library-gcc):

> The gcc option `-Wl` is a special option for passing options to the underlying linker. Syntax of this option differs from the other gcc options: It is followed by a comma-separated list of linker options, so that the linker options do not get mixed up with space-separated gcc options.

From your compiler output, you are passing GCC-specific options `-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/anaconda/envs/py37_default/lib -Wl,-rpath-link,/anaconda/envs/py37_default/lib` to `nvcc` in `LD_FLAGS`.

Use `-Xcompiler` to pass those GCC-specific options to `nvcc`. (from [this NVIDIA Developer forum post](https://forums.developer.nvidia.com/t/nvcc-fatal-unknown-option-wl-e/75396))

**Comment by XutongLi** [comment]
> From [Red Hat Developer Guide (Section 16.6)](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/developer_guide/gcc-using-libraries#gcc-using-libraries_using-both-static-dynamic-library-gcc):
> 
> > The gcc option `-Wl` is a special option for passing options to the underlying linker. Syntax of this option differs from the other gcc options: It is followed by a comma-separated list of linker options, so that the linker options do not get mixed up with space-separated gcc options.
> 
> From your compiler output, you are passing GCC-specific options `-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/anaconda/envs/py37_default/lib -Wl,-rpath-link,/anaconda/envs/py37_default/lib` to `nvcc` in `LD_FLAGS`.
> 
> Use `-Xcompiler` to pass those GCC-specific options to `nvcc`. (from [this NVIDIA Developer forum post](https://forums.developer.nvidia.com/t/nvcc-fatal-unknown-option-wl-e/75396))

In which file to add `-Xcomplier` ? I tried to add it to src/Makefile, but it didn't work
